### ISSUE TITLE
Crash when global warming causes waters to rise

### ISSUE THREAD

**Issue by lassefolkersen** [lassefolkersen/highfrontier#16]
To reproduce:
* Start new game, as company or country, doesn't matter
* Go to file menu > catastrophes > global warming - click it
* If done immediately it reacts as expected and waters rise. 
* But if the game has processed a bit, new zoom, stuff has happen (gotta figure out what), it crashes with the error message below:

```
Traceback (most recent call last):
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 396, in <module>
    introGui = IntroGui()
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 70, in __init__
    self.receive_click(event)
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 86, in receive_click
    button.activate(event)
  File "/Users/lassefolkersen/Documents/highfrontier/gui_components.py", line 499, in activate
    return_value = self.function(self.label, self.function_parameter)
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 30, in start_new_game
    self.main.start_loop(companyName = cn,
  File "/Users/lassefolkersen/Documents/highfrontier/main.py", line 124, in start_loop
    gui_instance.zoom()
  File "/Users/lassefolkersen/Documents/highfrontier/gui.py", line 256, in zoom
    surface = self.draw_display(sol.display_mode)
  File "/Users/lassefolkersen/Documents/highfrontier/gui.py", line 189, in draw_display
    surface = sol.current_planet.draw_entire_planet(
  File "/Users/lassefolkersen/Documents/highfrontier/planet.py", line 1171, in draw_entire_planet
    rgba_action_surface = self.draw_image(eastern_inclination, northern_inclination, projection_scaling, fast_rendering = True, image = rgba_action)
  File "/Users/lassefolkersen/Documents/highfrontier/planet.py", line 1136, in draw_image
    surface = pygame.image.frombuffer(image_bmp , (window_size[0],window_size[1]), mode)
ValueError: Buffer length does not equal format and resolution size
```

**Comment by lassefolkersen** [comment]
Ok, it seems to work when not zoomed into the most-zoomed in mode "flat world" - even with rising seas
![Screenshot 2024-05-08 at 09 28 12](https://github.com/lassefolkersen/highfrontier/assets/1732847/3735bfce-26d6-4925-9ef4-818ded74e22d)

It only crashes when zoomed all the way in, I guess that's a clue
